version: '3.4'

services:
########################################################## microservices.demo.product.api ################################################################################
  microservices.demo.product.api:
    image: ${DOCKER_REGISTRY-}microservicesdemoproductapi
    ports:
      - "80"
      - "443"
    build:
      context: .
      dockerfile: app/Domain/Microservices.Demo.Product.API/Dockerfile
    networks:
      - backend
########################################################## microservices.demo.pricing.api ################################################################################
  microservices.demo.pricing.api:
    image: ${DOCKER_REGISTRY-}microservicesdemopricingapi
    ports:
      - 80
      - 443
    build:
      context: .
      dockerfile: app/Domain/Microservices.Demo.Pricing.API/Dockerfile
    networks:
      - backend
########################################################## microservices.demo.policy.api #################################################################################
  microservices.demo.policy.api:
    image: ${DOCKER_REGISTRY-}microservicesdemopolicyapi
    ports:
      - 80
      - 443
    build:
      context: .
      dockerfile: app/Domain/Microservices.Demo.Policy.API/Dockerfile
    networks:
      - backend
########################################################## microservices.demo.auth.api ###################################################################################
  microservices.demo.auth.api:
    image: ${DOCKER_REGISTRY-}microservicesdemoauthapi
    ports:
      - 80
      - 443
    build:
      context: .
      dockerfile: app/Infrastructure/Microservices.Demo.Auth.API/Dockerfile
    networks:
      - backend
########################################################## microservices.demo.client.web.apigateway ######################################################################
  microservices.demo.client.web.apigateway:
    image: ${DOCKER_REGISTRY-}microservicesdemoclientwebapigateway
    ports:
      - 80
      - 44399:443
    build:
      context: .
      dockerfile: app/Infrastructure/Microservices.Demo.Client.Web.ApiGateway/Dockerfile
    networks:
      - backend
########################################################## networks ######################################################################################################
networks:
  backend:
    name: backend
    driver: bridge


